config/routes.rb
Rails.application.routes.draw do
  get 'gossips/:id', to: 'gossips#show', as: 'gossips'
  get 'welcome/:user_entry', to: 'welcome#show'
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: 'static_pages#index'
  get 'user/:id', to: 'user#show', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :comments
	has_many :likes
	has_many :gossips_tags
	has_many :tags, through: :gossips_tags
end

app/models/gossips_tag.rb
class GossipsTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips_tags
	has_many :gossips, through: :gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :comments
	has_many :likes
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :email,
    presence: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end
  def contact
  end
  def index
    @gossip = Gossip.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    puts "$" * 60
        puts "Voici le message de l'URL :"
        puts  params[:user_entry]
        puts "$" * 60
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/show.html.erb
<div class="card">
  <div class="card-header">
    <h1><u>Gossip # <%= params[:id] %></u></h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Titre : <%= @gossip.title %></h5>
    <p class="card-text">Le super ragot : "<%= @gossip.content %>"</p>
    <p>Date de création : <%= @gossip.created_at %></p>
    <%= link_to "Page Auteur", user_path(@gossip.user.id), :class => "btn-info btn" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- css bootstrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body">

    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "The Potin Project", home_path, :class => "navbar-brand" %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Contact", contact_path, :class => "nav-item", :class => "nav-link" %>
          <%= link_to "Team", team_path, :class => "nav-item nav-link" %>
        </div>
      </div>
    </nav>

  <div class= "ml-2 mt-2" >
    <%= yield %>
  </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<div class="card">
  <div class="card-header">
    <h1>Team à l'arrache</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Moussaillons: Claudia et Maxence</h5>
    <p class="card-text">📧 email de Claudia: claudiapartonnau@gmail.com <br/>
      📧 email de Maxence: kiger.maxence@gmail.com </p>
  </div>
</div>

app/views/static_pages/index.html.erb
<h1>Bienvenue sur la page des Potins !</h1>
  <div class="card-columns">
  <% @gossip.each do |i| %>
    <div class="card" style="width: 18rem;">
      <div class="card-header"><h5 class="card-title"><%= i.title %></h5></div>
      <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted"><%= i.user.first_name %></h6>
        <%= link_to "Go Potin", gossips_path(i.user.id),:class => "btn-info btn p-1"%>
      </div>
    </div>
  <% end %>
</div>

app/views/static_pages/team.html.erb
 <div class="card">
  <div class="card-header">
    <h1>Team à l'arrache</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Moussaillons: Claudia et Maxence</h5>
  </div>
</div>

app/views/user/show.html.erb
<div class="card border-info">
  <div class="card-header">
    <h1><u><%= @user.first_name + " " + @user.last_name  %></u></h1>
  </div>
  <div class="card-body text-info">
    <ul class="card-text">
      <li>Prénom : <%= @user.first_name %></li>
      <li>Nom : <%= @user.last_name %></li>
      <li>Email : <%= @user.email %></li>
      <li>Bio : <%= @user.description %></li>
      <li>Âge : <%= @user.age %></li>
      <li>Ville : <%= @user.city.name %></li>
    </ul>
  </div>
  <div class="card-footer"><h2><u>Potins:</u></h2><% @user.gossips.each do |i| %>
  <blockquote class="blockquote font-italic">"<%= i.content %>"</blockquote>
  <%end%></div>
</div>

app/views/welcome/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">BIENVENUE <%= params[:user_entry].capitalize %> !</h1>
    <p class="lead">Ici c'est notre super site de potins, il est chouette, non ?</p>
  </div>
</div>